name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Configuration'
    labels:
      - 'config'
      - 'configuration'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🏗️ Build System'
    labels:
      - 'build'
      - 'ci'
      - 'workflow'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add ` and \ to escapes if needed.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch
filter:
  branches:
    - main
    - master
    - develop
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Full Changelog

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
